[package]
name = "mathlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = {version = "0.8.5", default_features = false, features = ["std_rng", "std"]}

[profile.dev]
opt-level = "s"